'use strict';
//debugger;

shimstar.C = Object.freeze({
    C_MESSAGE_LOGIN : "1",
    C_MESSAGE_UPDATE_MISSION : "2",
    C_MESSAGE_ACCEPT_MISSION : "3",
    C_MESSAGE_PROPOSE_MISSION : "4",
    C_MESSAGE_CREATE_USER : "5",
    C_MESSAGE_INFO_USER : "6",
    C_MESSAGE_CREATE_USER : "7",

    C_MISSION_STATUS_NEW : "1",
    C_MISSION_STATUS_ACCEPTED : "2",
    C_MISSION_STATUS_REFUSED : "3",
    C_MISSION_STATUS_FINISHED : "4",
    C_MISSION_STATUS_INPROGRESS : "5",

    C_MISSION_TYPE_DESTROY : "1",
    C_MISSION_TYPE_PROTECT : "2",
    C_MISSION_TYPE_TRANSPORT : "3"
});
